language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
install
  # Install the lighter miniconda3
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Use conda to install Python 3.5 and the deps in my environment file
  - conda env create -q QUIET --file environment.yml
  - source activate exercism

script:
  - nosetests */*_test.py 
