contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://willjharmer.github.io/exercism-python"
title: "Exercism Python"
canonifyurls: true
params:
  description: "Practising TDD idiomatic python"
  author_url: "http://github.com/willjharmer"
  project_url: "http://github.com/willjharmer/exercism-python"
  github_user_name: "willjharmer"
  travis_badge: "https://travis-ci.org/willjharmer/exercism-python.svg?branch=develop"

  first_color: "#f8f8f8"
  first_border_color: "#e7e7e7"
  first_text_color: "#333"

  second_color: "white"
  second_text_color: "#333"

  header_color: "#f8f8f8"
  header_text_color: "rgb(51, 51, 51)"

  header_link_color: "#777"
  header_link_hover_color: "rgb(51, 51, 51)"
